<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>seatunnel-dist</artifactId>
    <name>SeaTunnel : Dist</name>

    <properties>
        <!-- disable mvn deploy to central maven repo by default -->
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <build>
        <finalName>apache-seatunnel-${project.version}</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bin</id>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/assembly-bin-ci.xml</descriptor>
                            </descriptors>
                            <appendAssemblyId>true</appendAssemblyId>
                        </configuration>
                    </execution>
                    <execution>
                        <id>src</id>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/assembly-src.xml</descriptor>
                            </descriptors>
                            <appendAssemblyId>true</appendAssemblyId>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>seatunnel</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>release</name>
                    <value>false</value>
                </property>
            </activation>
            <properties>
                <mysql.version>8.0.27</mysql.version>
                <postgresql.version>42.4.3</postgresql.version>
                <oracle.version>18.3.0.0</oracle.version>
                <hive.version>3.1.0</hive.version>
                <clickhouse.version>0.2.6</clickhouse.version>

                <!-- Imap storage dependency package  -->
                <hadoop-aliyun.version>3.1.4</hadoop-aliyun.version>
                <json-smart.version>2.4.7</json-smart.version>
                <hadoop-aws.version>3.1.4</hadoop-aws.version>
                <aws-java-sdk.version>1.11.271</aws-java-sdk.version>
                <netty-buffer.version>4.1.89.Final</netty-buffer.version>
                <hive.exec.version>3.1.3</hive.exec.version>
                <hive.jdbc.version>3.1.3</hive.jdbc.version>
                <aliyun.sdk.oss.version>3.4.1</aliyun.sdk.oss.version>
                <jdom.version>1.1</jdom.version>
            </properties>
            <dependencies>
                <!-- starters -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!-- transforms -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-transforms-v2</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-clickhouse</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-jdbc</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-elasticsearch</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-kafka</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hw-kafka</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hw-elasticsearch</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-hive</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-hadoop</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-local</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-ftp</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-file-sftp</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-elasticsearch</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-redis</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-mongodb</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-doris</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-cdc-mysql</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- jdbc driver -->
                <dependency>
                    <groupId>mysql</groupId>
                    <artifactId>mysql-connector-java</artifactId>
                    <version>${mysql.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                    <version>${postgresql.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>com.oracle.database.jdbc</groupId>
                    <artifactId>ojdbc8</artifactId>
                    <version>${oracle.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!--                <dependency>-->
                <!--                    <groupId>org.apache.hive</groupId>-->
                <!--                    <artifactId>hive-jdbc</artifactId>-->
                <!--                    <version>${hive.jdbc.version}</version>-->
                <!--                    <scope>provided</scope>-->
                <!--                </dependency>-->
                <dependency>
                    <groupId>ru.yandex.clickhouse</groupId>
                    <artifactId>clickhouse-jdbc</artifactId>
                    <version>${clickhouse.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- jdbc driver end -->

                <dependency>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-buffer</artifactId>
                    <version>${netty-buffer.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- hadoop jar -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
                <!-- hadoop jar end -->
                <!-- hive jar start -->
                <dependency>
                    <groupId>org.apache.hive</groupId>
                    <artifactId>hive-exec</artifactId>
                    <version>${hive.exec.version}</version>
                    <scope>provided</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>log4j</groupId>
                            <artifactId>log4j</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-1.2-api</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-slf4j-impl</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-web</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.slf4j</groupId>
                            <artifactId>slf4j-log4j12</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.parquet</groupId>
                            <artifactId>parquet-hadoop-bundle</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>jdk.tools</groupId>
                            <artifactId>jdk.tools</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.pentaho</groupId>
                            <artifactId>pentaho-aggdesigner-algorithm</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.avro</groupId>
                            <artifactId>avro</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>org.apache.thrift</groupId>
                    <artifactId>libfb303</artifactId>
                    <version>0.9.3</version>
                    <type>pom</type>
                    <scope>provided</scope>
                </dependency>
                <!-- hive jdbc jar -->
                <dependency>
                    <groupId>org.apache.hive</groupId>
                    <artifactId>hive-jdbc</artifactId>
                    <version>${hive.jdbc.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.hive</groupId>
                    <artifactId>hive-service</artifactId>
                    <version>${hive.jdbc.version}</version>
                    <scope>provided</scope>
                    <exclusions>
                        <exclusion>
                            <groupId>log4j</groupId>
                            <artifactId>log4j</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-1.2-api</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-slf4j-impl</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.logging.log4j</groupId>
                            <artifactId>log4j-web</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.slf4j</groupId>
                            <artifactId>slf4j-log4j12</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.parquet</groupId>
                            <artifactId>parquet-hadoop-bundle</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>jdk.tools</groupId>
                            <artifactId>jdk.tools</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.pentaho</groupId>
                            <artifactId>pentaho-aggdesigner-algorithm</artifactId>
                        </exclusion>
                        <exclusion>
                            <groupId>org.apache.avro</groupId>
                            <artifactId>avro</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <!-- hive jar end -->
            </dependencies>
            <repositories>
                <repository>
                    <id>cloudera</id>
                    <url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
                </repository>

            </repositories>
        </profile>
        <profile>
            <id>release</id>
            <activation>
                <property>
                    <name>release</name>
                    <value>true</value>
                </property>
            </activation>
            <dependencies>
                <!-- starters -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-flink-13-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-flink-15-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-spark-2-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-spark-3-starter</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <!-- seatunnel connectors for demo -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-fake</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>connector-console</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <!-- transforms v2 -->
                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-transforms-v2</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                </dependency>

                <dependency>
                    <groupId>org.apache.seatunnel</groupId>
                    <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
                    <version>${project.version}</version>
                    <classifier>optional</classifier>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
            <build>
                <finalName>apache-seatunnel-${project.version}</finalName>
                <plugins>
                    <plugin>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>bin</id>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <phase>package</phase>
                                <configuration>
                                    <descriptors>
                                        <descriptor>src/main/assembly/assembly-bin.xml</descriptor>
                                    </descriptors>
                                    <appendAssemblyId>true</appendAssemblyId>
                                </configuration>
                            </execution>

                            <execution>
                                <id>src</id>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                                <phase>package</phase>
                                <configuration>
                                    <descriptors>
                                        <descriptor>src/main/assembly/assembly-src.xml</descriptor>
                                    </descriptors>
                                    <appendAssemblyId>true</appendAssemblyId>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
